x-default-policy: &default_policy
  restart: unless-stopped
  networks:
    - ochacafe

services:
  init:
    image: &tempoImage grafana/tempo:2.6.1
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/var/tempo"
    volumes:
      - tempo-data:/var/tempo
    networks:
      - ochacafe
  memcached:
    <<: *default_policy
    image: memcached:1.6.29
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      - MEMCACHED_MAX_MEMORY=64m # Set the maximum memory usage
      - MEMCACHED_THREADS=4 # Number of threads to use
  tempo:
    <<: *default_policy
    image: *tempoImage
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./config/tempo.yaml:/etc/tempo.yaml
      - tempo-data:/var/tempo
    ports:
      - "4317" # otlp grpc
      - "4318" # otlp http
    depends_on:
      - init
      - memcached
  otel-collector:
    <<: *default_policy
    image: otel/opentelemetry-collector-contrib
    container_name: otel-collector
    volumes:
      - ./config/otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
  loki-init:
    image: &lokiImage grafana/loki:3.3.0
    user: root
    entrypoint:
      - "chown"
      - "10001:10001"
      - "/tmp/loki"
    volumes:
      - loki-data:/tmp/loki
    networks:
      - ochacafe
  loki:
    <<: *default_policy
    container_name: loki
    image: *lokiImage
    command: "-config.file=/etc/loki/loki.yaml"
    environment:
      LOG_CLUSTER_DEPTH: "8"
      LOG_SIM_TH: "0.3"
    volumes:
      - ./config/loki.yaml:/etc/loki/loki.yaml
      - loki-data:/tmp/loki
    ports:
      - 3100:3100
      - 7946
      - 9095
    depends_on:
      - loki-init
  prometheus:
    <<: *default_policy
    image: prom/prometheus:v3.0.0
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
      - --enable-feature=native-histograms
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - "9090:9090"
  grafana:
    <<: *default_policy
    image: grafana/grafana:11.2.0
    container_name: grafana
    volumes:
      - ./config/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"

volumes:
  tempo-data:
  loki-data:
networks:
  ochacafe:
